<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1866" started-at="2021-02-24T03:25:23Z" finished-at="2021-02-24T03:25:25Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="1866" started-at="2021-02-24T03:25:23Z" finished-at="2021-02-24T03:25:25Z">
      <class name="org.testing.TestScripts.TC4">
        <test-method status="PASS" signature="testcase4()[pri:0, instance:org.testing.TestScripts.TC4@124c278f]" name="testcase4" duration-ms="63" started-at="2021-02-24T14:25:25Z" finished-at="2021-02-24T14:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
      </class> <!-- org.testing.TestScripts.TC4 -->
      <class name="org.testing.TestScripts.TC3">
        <test-method status="PASS" signature="testcase3()[pri:0, instance:org.testing.TestScripts.TC3@61dd025]" name="testcase3" duration-ms="53" started-at="2021-02-24T14:25:25Z" finished-at="2021-02-24T14:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3 -->
      </class> <!-- org.testing.TestScripts.TC3 -->
      <class name="org.testing.TestScripts.TC5">
        <test-method status="PASS" signature="testcase5()[pri:0, instance:org.testing.TestScripts.TC5@15b204a1]" name="testcase5" duration-ms="53" started-at="2021-02-24T14:25:25Z" finished-at="2021-02-24T14:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase5 -->
      </class> <!-- org.testing.TestScripts.TC5 -->
      <class name="org.testing.TestScripts.TC2">
        <test-method status="PASS" signature="testcase2()[pri:0, instance:org.testing.TestScripts.TC2@147ed70f]" name="testcase2" duration-ms="100" started-at="2021-02-24T14:25:25Z" finished-at="2021-02-24T14:25:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
      </class> <!-- org.testing.TestScripts.TC2 -->
      <class name="org.testing.TestScripts.TC1">
        <test-method status="FAIL" signature="testcase1()[pri:0, instance:org.testing.TestScripts.TC1@29176cc1]" name="testcase1" duration-ms="1534" started-at="2021-02-24T14:25:23Z" finished-at="2021-02-24T14:25:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code is not matching so failed expected [200] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code is not matching so failed expected [200] but found [201]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testing.ResponseValidation.Responsehandling.responseStatusCode(Responsehandling.java:11)
	at org.testing.TestScripts.TC1.testcase1(TC1.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
      </class> <!-- org.testing.TestScripts.TC1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
